server:
  port: 8760
  servlet:
    context-path: /franc/discovery
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: franc-discovery

  output:
    ansi:
      enabled: always

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

#  web:
#    resources:
#      add-mappings: false

# 유레카 서버 설정
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  config: classpath:log4j2.xml